# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stefano_vecchiati_test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'R.swift'

#pod 'Reveal-SDK', :configurations => ['Debug']

pod 'LifetimeTracker', :configurations => ['Debug']

pod 'SteviaLayout'

pod 'Cosmos'

end
